<Project>

  <PropertyGroup>
    <MicrosoftNetTestSdkVersion>18.10.1</MicrosoftNetTestSdkVersion>
    <XunitAnalyzersVersion>2.1.0</XunitAnalyzersVersion>
    <XunitVersion>2.9.3</XunitVersion>
    <!-- Stuck to 2.x due to minimum target framework changes in later versions -->
    <XunitRunnerVSVersion>[2.8.2]</XunitRunnerVSVersion>
  </PropertyGroup>

</Project>